using System.Diagnostics;
using System.Diagnostics.Metrics;

namespace Agentic.Core;

/// <summary>
/// Central observability hub for Agentic.NET.
/// Exposes a single <see cref="ActivitySource"/> (for distributed tracing) and a single
/// <see cref="Meter"/> (for metrics) that consumers wire into their OpenTelemetry pipelines.
/// </summary>
/// <remarks>
/// To collect traces, add the source name to your TracerProviderBuilder:
/// <code>
/// services.AddOpenTelemetry()
///     .WithTracing(b => b.AddSource(AgenticTelemetry.ActivitySourceName))
///     .WithMetrics(b => b.AddMeter(AgenticTelemetry.MeterName));
/// </code>
/// No configuration is needed inside the library itself — instrumentation activates
/// automatically whenever a listener is registered.
/// </remarks>
public static class AgenticTelemetry
{
    /// <summary>The name of the <see cref="ActivitySource"/> used by Agentic.NET.</summary>
    public const string ActivitySourceName = "Agentic.NET";

    /// <summary>The name of the <see cref="Meter"/> used by Agentic.NET.</summary>
    public const string MeterName = "Agentic.NET";

    internal static readonly ActivitySource ActivitySource =
        new(ActivitySourceName, ThisAssembly.Version);

    internal static readonly Meter Meter =
        new(MeterName, ThisAssembly.Version);

    // ── Metrics ──────────────────────────────────────────────────────────────

    /// <summary>Total number of <c>ReplyAsync</c> calls completed (labelled by model).</summary>
    internal static readonly Counter<long> ReplyCounter =
        Meter.CreateCounter<long>(
            "agentic.reply.count",
            unit: "{reply}",
            description: "Number of agent reply turns completed.");

    /// <summary>End-to-end duration of a single <c>ReplyAsync</c> call in milliseconds.</summary>
    internal static readonly Histogram<double> ReplyDuration =
        Meter.CreateHistogram<double>(
            "agentic.reply.duration",
            unit: "ms",
            description: "Duration of agent reply turns from input received to response returned.");

    /// <summary>Total number of LLM completion calls.</summary>
    internal static readonly Counter<long> LlmCallCounter =
        Meter.CreateCounter<long>(
            "agentic.llm.call.count",
            unit: "{call}",
            description: "Number of LLM completion calls made.");

    /// <summary>Total prompt tokens consumed across all LLM calls.</summary>
    internal static readonly Counter<long> PromptTokenCounter =
        Meter.CreateCounter<long>(
            "agentic.llm.prompt_tokens",
            unit: "{token}",
            description: "Total prompt tokens sent to the LLM.");

    /// <summary>Total completion tokens generated across all LLM calls.</summary>
    internal static readonly Counter<long> CompletionTokenCounter =
        Meter.CreateCounter<long>(
            "agentic.llm.completion_tokens",
            unit: "{token}",
            description: "Total completion tokens generated by the LLM.");

    /// <summary>Total number of tool invocations.</summary>
    internal static readonly Counter<long> ToolCallCounter =
        Meter.CreateCounter<long>(
            "agentic.tool.call.count",
            unit: "{call}",
            description: "Number of tool calls executed by the agent.");

    /// <summary>Duration of individual tool executions in milliseconds.</summary>
    internal static readonly Histogram<double> ToolCallDuration =
        Meter.CreateHistogram<double>(
            "agentic.tool.call.duration",
            unit: "ms",
            description: "Duration of individual tool invocations.");

    /// <summary>Total number of memory retrieval operations.</summary>
    internal static readonly Counter<long> MemoryRetrievalCounter =
        Meter.CreateCounter<long>(
            "agentic.memory.retrieval.count",
            unit: "{retrieval}",
            description: "Number of memory retrieval operations performed.");

    /// <summary>Number of items returned per memory retrieval.</summary>
    internal static readonly Histogram<int> MemoryRetrievalItems =
        Meter.CreateHistogram<int>(
            "agentic.memory.retrieval.items",
            unit: "{item}",
            description: "Number of memory items returned per retrieval.");

    /// <summary>Total number of heartbeat ticks that reached the model.</summary>
    internal static readonly Counter<long> HeartbeatCounter =
        Meter.CreateCounter<long>(
            "agentic.heartbeat.count",
            unit: "{tick}",
            description: "Number of heartbeat ticks that invoked the model.");

    /// <summary>Wall-clock duration of a heartbeat tick in milliseconds.</summary>
    internal static readonly Histogram<double> HeartbeatDuration =
        Meter.CreateHistogram<double>(
            "agentic.heartbeat.duration",
            unit: "ms",
            description: "Duration of a heartbeat tick from start to completion.");

    /// <summary>Total number of heartbeat ticks that were skipped (labelled by reason).</summary>
    internal static readonly Counter<long> HeartbeatSkipCounter =
        Meter.CreateCounter<long>(
            "agentic.heartbeat.skip.count",
            unit: "{tick}",
            description: "Number of heartbeat ticks that were skipped without invoking the model.");

    // ── Span / tag name constants (Gen AI semantic conventions) ─────────────

    // https://opentelemetry.io/docs/specs/semconv/gen-ai/

    internal static class Tags
    {
        // gen_ai.*
        public const string GenAiSystem       = "gen_ai.system";
        public const string GenAiOperation    = "gen_ai.operation.name";
        public const string GenAiModel        = "gen_ai.request.model";
        public const string PromptTokens      = "gen_ai.usage.input_tokens";
        public const string CompletionTokens  = "gen_ai.usage.output_tokens";

        // agentic.*  (library-specific)
        public const string AgentToolName     = "agentic.tool.name";
        public const string AgentToolSuccess  = "agentic.tool.success";
        public const string AgentHistoryLen   = "agentic.history.length";
        public const string AgentMemoryItems  = "agentic.memory.items";
        public const string AgentMemoryMode   = "agentic.memory.mode";   // "keyword" | "semantic"
        public const string HeartbeatSkipReason = "agentic.heartbeat.skip_reason";
    }

    // ── Span name constants ───────────────────────────────────────────────────

    internal static class Spans
    {
        public const string Reply           = "agent.reply";
        public const string LlmComplete     = "llm.complete";
        public const string ToolCall        = "tool.call";
        public const string MemoryRetrieval = "memory.retrieval";
        public const string Heartbeat       = "agent.heartbeat";
    }

    // ── Private helper ────────────────────────────────────────────────────────

    private static class ThisAssembly
    {
        // Resolved at startup from the executing assembly's version string.
        public static readonly string Version =
            typeof(AgenticTelemetry).Assembly.GetName().Version?.ToString(3) ?? "0.0.0";
    }
}
